development:
  host: localhost
  database: awesomeness_shdhsg_development

test:
  host: localhost
  database: awesomeness_shdhsg_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
