development:
  host: localhost
  database: namecard_development

test:
  host: localhost
  database: namecard_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
